#!/usr/bin/env python3
"""Verify every [[sources]] entry in fixtures/corpora/gutenberg.toml
matches its on-disk source blob by sha256.

This is a sanity-check pass for whoever consumes the fixture next: if
the pin file drifts from the actual harvested bytes (e.g. someone
re-runs fetch_plaintext.py with a different selection), this gate will
catch it before F-S4.05 build-corpus does — and produce a more useful
diff than a stack trace from the manifest assembler.

Outputs to stdout + writes docs/experiments/S4-fixture-pin-validation.md
"""
from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path


def parse_sources(toml_text: str) -> list[dict]:
    """Tiny line-oriented [[sources]] parser. We only need three fields
    (book_id, source_blob_sha256, local_blob_path); a full toml parser
    isn't in the stdlib on this Python version.
    """
    records: list[dict] = []
    cur: dict | None = None
    field_re = re.compile(r"^(\w+)\s*=\s*(.*)$")
    for raw in toml_text.splitlines():
        line = raw.strip()
        if line == "[[sources]]":
            if cur is not None:
                records.append(cur)
            cur = {}
            continue
        if line.startswith("["):
            # End of [[sources]] block, hit some other table.
            if cur is not None:
                records.append(cur)
                cur = None
            continue
        if cur is None:
            continue
        m = field_re.match(line)
        if not m:
            continue
        key, val = m.group(1), m.group(2).strip()
        if val.startswith('"') and val.endswith('"'):
            val = val[1:-1]
        cur[key] = val
    if cur is not None:
        records.append(cur)
    return records


def main() -> int:
    repo = Path(__file__).resolve().parents[3]
    pin = repo / "fixtures/corpora/gutenberg.toml"
    sources = parse_sources(pin.read_text())
    print(f"parsed {len(sources)} [[sources]] entries", file=sys.stderr)

    ok = 0
    missing = []
    mismatch = []
    for i, rec in enumerate(sources):
        bid = rec.get("book_id")
        pin_sha = rec.get("source_blob_sha256")
        local = rec.get("local_blob_path")
        if not (bid and pin_sha and local):
            missing.append({"book_id": bid, "reason": "missing required field"})
            continue
        blob_path = repo / local
        if not blob_path.exists():
            missing.append({"book_id": bid, "local_blob_path": local})
            continue
        h = hashlib.sha256()
        with blob_path.open("rb") as f:
            for chunk in iter(lambda: f.read(1 << 20), b""):
                h.update(chunk)
        got = h.hexdigest()
        if got != pin_sha:
            mismatch.append({
                "book_id": bid,
                "pin": pin_sha,
                "got": got,
                "local_blob_path": local,
            })
        else:
            ok += 1
        if (i + 1) % 200 == 0:
            print(f"  ... {i + 1}/{len(sources)} verified (ok={ok}, "
                  f"missing={len(missing)}, mismatch={len(mismatch)})", file=sys.stderr)

    print(f"\nverified {ok} / {len(sources)} ({100 * ok / max(1, len(sources)):.2f}%)")
    print(f"missing blobs: {len(missing)}")
    print(f"sha256 mismatches: {len(mismatch)}")

    docs = repo / "docs/experiments/S4-fixture-pin-validation.md"
    md = [
        "# F-S4 Fixture Pin Validation",
        "",
        "Walks every `[[sources]]` entry in `fixtures/corpora/gutenberg.toml`",
        "and recomputes sha256 over the on-disk source blob to confirm the pin",
        "file is in lockstep with the harvested bytes. Generated by",
        "`scripts/corpus/gutenberg/validate_full_fixture.py`.",
        "",
        "## Result",
        "",
        f"- **Total `[[sources]]` records:** {len(sources)}",
        f"- **Sha256 verified (pin == on-disk):** {ok}",
        f"- **Missing local blob:** {len(missing)}",
        f"- **Sha256 mismatch:** {len(mismatch)}",
        f"- **Pass rate:** {100 * ok / max(1, len(sources)):.2f}%",
        "",
    ]
    if mismatch or missing:
        md.append("## ⚠️ Issues")
        md.append("")
        if missing:
            md.append("### Missing on-disk blobs")
            for m in missing[:10]:
                md.append(f"- book_id={m.get('book_id')} local_blob_path={m.get('local_blob_path')}")
            if len(missing) > 10:
                md.append(f"- … and {len(missing) - 10} more")
            md.append("")
        if mismatch:
            md.append("### Sha256 mismatches (first 10)")
            for m in mismatch[:10]:
                md.append(f"- book_id={m['book_id']} pin={m['pin'][:16]}… got={m['got'][:16]}…")
            if len(mismatch) > 10:
                md.append(f"- … and {len(mismatch) - 10} more")
            md.append("")
    else:
        md.extend([
            "## ✓ Clean",
            "",
            "Every pinned source_blob_sha256 matches its on-disk blob byte-for-byte.",
            "The fixture pin file and the harvested bytes are in lockstep.",
            "",
        ])
    md.append(
        "_Run this script before claiming F-S4.05 (build-corpus). Any drift here "
        "becomes a downstream manifest_self_hash mismatch in CI._"
    )
    docs.write_text("\n".join(md) + "\n")
    print(f"wrote {docs}")
    return 0 if (not mismatch and not missing) else 1


if __name__ == "__main__":
    sys.exit(main())
