use gbf_abi::{
    CompactCheckpointId, FaultCode, FaultCodeOptional, FaultSnapshot, InferenceStateHeader,
    LivenessCounters, RegisterSnapshot, SliceId, decode_header, split_header_tail,
};
use proptest::prelude::*;
use proptest::test_runner::{Config, RngSeed, TestRunner};

#[derive(Debug, Clone)]
enum LivenessEvent {
    Progress(CompactCheckpointId),
    Idle,
}

fn runner(seed: u64) -> TestRunner {
    TestRunner::new(Config {
        cases: 128,
        failure_persistence: None,
        rng_seed: RngSeed::Fixed(seed),
        ..Config::default()
    })
}

fn liveness_event() -> impl Strategy<Value = LivenessEvent> {
    prop_oneof![
        any::<u16>().prop_map(|raw| LivenessEvent::Progress(CompactCheckpointId(raw))),
        Just(LivenessEvent::Idle),
    ]
}

fn fault_code() -> impl Strategy<Value = FaultCode> {
    prop::sample::select(FaultCode::ALL.to_vec())
}

fn non_none_fault_code() -> impl Strategy<Value = FaultCode> {
    let codes = FaultCode::ALL
        .iter()
        .copied()
        .filter(|code| *code != FaultCode::None)
        .collect::<Vec<_>>();
    prop::sample::select(codes)
}

fn fault_code_optional() -> impl Strategy<Value = FaultCodeOptional> {
    prop_oneof![
        Just(FaultCodeOptional::NONE),
        non_none_fault_code().prop_map(|code| FaultCodeOptional::from_option(Some(code))),
    ]
}

fn register_snapshot() -> impl Strategy<Value = RegisterSnapshot> {
    (
        any::<u8>(),
        any::<u8>(),
        any::<u8>(),
        any::<u8>(),
        any::<u8>(),
        any::<u8>(),
        any::<u8>(),
        any::<u8>(),
        any::<u16>(),
    )
        .prop_map(|(a, f, b, c, d, e, h, l, sp)| RegisterSnapshot {
            a,
            f,
            b,
            c,
            d,
            e,
            h,
            l,
            sp,
        })
}

fn liveness_counters() -> impl Strategy<Value = LivenessCounters> {
    (any::<u16>(), any::<u32>(), any::<u16>(), any::<u16>()).prop_map(
        |(threshold, progress_epoch, last_checkpoint, no_progress_frames)| {
            let mut counters = LivenessCounters::new(threshold);
            counters.progress_epoch = progress_epoch;
            counters.last_checkpoint = CompactCheckpointId(last_checkpoint);
            counters.no_progress_frames = no_progress_frames;
            counters
        },
    )
}

fn continuation_header() -> impl Strategy<Value = InferenceStateHeader> {
    (
        1u16..=u16::MAX,
        any::<u32>(),
        any::<u32>(),
        any::<u32>(),
        fault_code_optional(),
        liveness_counters(),
    )
        .prop_map(
            |(schema, session_id, token_count, slice_id, last_fault, liveness)| {
                let mut header = InferenceStateHeader::new(
                    schema,
                    session_id,
                    liveness.livelock_threshold_frames,
                );
                header.last_fault = last_fault;
                header.token_count = token_count;
                header.slice_id = SliceId(slice_id);
                header.liveness = liveness;
                header
            },
        )
}

#[test]
fn fault_snapshot_from_to_bytes_round_trip_property() {
    let strategy = (
        fault_code(),
        any::<u16>(),
        any::<u16>(),
        any::<u16>(),
        register_snapshot(),
        liveness_counters(),
    );
    runner(0xFA3_0003)
        .run(
            &strategy,
            |(code, at_pc, at_bank, at_checkpoint, regs, liveness)| {
                let snapshot = FaultSnapshot::new(
                    code,
                    at_pc,
                    at_bank,
                    CompactCheckpointId(at_checkpoint),
                    regs,
                    liveness,
                );
                let bytes = snapshot.to_bytes();
                let decoded = FaultSnapshot::from_bytes(&bytes).expect("generated bytes validate");

                prop_assert_eq!(FaultCode::from_u16(decoded.code), Some(code));
                prop_assert_eq!(decoded, snapshot);
                prop_assert_eq!(decoded.to_bytes(), bytes);

                Ok(())
            },
        )
        .expect("deterministic fault snapshot round-trip property holds");
}

#[test]
fn continuation_header_from_to_bytes_round_trip_property() {
    let strategy = (
        continuation_header(),
        prop::collection::vec(any::<u8>(), 0..64),
    );
    runner(0xFA3_0004)
        .run(&strategy, |(header, tail)| {
            let bytes = header.to_bytes();
            let decoded = decode_header(&bytes).expect("generated header validates");
            prop_assert_eq!(decoded, header);
            prop_assert_eq!(decoded.to_bytes(), bytes);

            let mut continuation = bytes.to_vec();
            continuation.extend_from_slice(&tail);
            let (split_header, split_tail) =
                split_header_tail(&continuation, tail.len() as u32).expect("tail length matches");
            prop_assert_eq!(split_header, header);
            prop_assert_eq!(split_tail, tail.as_slice());

            Ok(())
        })
        .expect("deterministic continuation header round-trip property holds");
}

#[test]
fn record_progress_then_idle_frame_property() {
    let strategy = (
        any::<u16>(),
        any::<u32>(),
        any::<u16>(),
        prop::collection::vec(liveness_event(), 0..256),
    );
    runner(0xFA3_0001)
        .run(&strategy, |(threshold, start_epoch, start_idle, events)| {
            let mut counters = LivenessCounters::new(threshold);
            counters.progress_epoch = start_epoch;
            counters.no_progress_frames = start_idle;

            for event in events {
                let before_epoch = counters.progress_epoch;
                let before_idle = counters.no_progress_frames;
                match event {
                    LivenessEvent::Progress(checkpoint) => {
                        counters.record_progress(checkpoint);
                        prop_assert_eq!(counters.progress_epoch, before_epoch.saturating_add(1));
                        prop_assert_eq!(counters.last_checkpoint, checkpoint);
                        prop_assert_eq!(counters.no_progress_frames, 0);
                    }
                    LivenessEvent::Idle => {
                        counters.note_idle_frame();
                        prop_assert_eq!(counters.progress_epoch, before_epoch);
                        prop_assert_eq!(counters.no_progress_frames, before_idle.saturating_add(1));
                    }
                }

                prop_assert_eq!(
                    counters.is_livelocked(),
                    counters.livelock_threshold_frames != 0
                        && counters.no_progress_frames >= counters.livelock_threshold_frames
                );
            }

            Ok(())
        })
        .expect("deterministic liveness property holds");
}

#[test]
#[cfg(feature = "host")]
fn schema_resolve_round_trip_property() {
    use gbf_abi::{
        CURRENT_ABI, CheckpointEntry, SemanticCheckpointId, SemanticCheckpointSchema,
        SemanticStratum,
    };
    use std::borrow::Cow;

    let strategy = prop::collection::btree_set(1u16..u16::MAX, 0..64);
    runner(0xFA3_0002)
        .run(&strategy, |compact_ids| {
            let checkpoints = compact_ids
                .into_iter()
                .map(|raw| {
                    let semantic = SemanticCheckpointId::from_owned(format!("checkpoint.{raw}"))
                        .expect("generated semantic id is valid");
                    let stratum = match raw % 3 {
                        0 => SemanticStratum::Denotation,
                        1 => SemanticStratum::Artifact,
                        _ => SemanticStratum::Operational,
                    };
                    CheckpointEntry {
                        semantic,
                        compact: CompactCheckpointId(raw),
                        stratum,
                        source_op: Some(Cow::Owned(format!("op_{raw}"))),
                    }
                })
                .collect();

            let schema = SemanticCheckpointSchema {
                schema_version: 1,
                abi_version: CURRENT_ABI,
                build_hash: [1; 32],
                compile_request_hash: [2; 32],
                checkpoints,
            };

            schema.validate().expect("generated schema is valid");
            for entry in &schema.checkpoints {
                prop_assert_eq!(
                    schema.resolve_semantic(&entry.semantic),
                    Some(entry.compact)
                );
                prop_assert_eq!(schema.resolve_compact(entry.compact), Some(&entry.semantic));
            }

            Ok(())
        })
        .expect("deterministic checkpoint schema property holds");
}
