#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out_dir="${1:-$repo_root/gbf-experiments/tests/fixtures/tiny_corpus}"
fixture_rel_dir="."
master_seed="${S1_TINY_FIXTURE_MASTER_SEED:-0xC0FFEE}"
val_seed_xor_mask="0xA5A5_A5A5_A5A5_A5A5"
train_len="${S1_TINY_FIXTURE_TRAIN_BYTES:-16384}"
val_len="${S1_TINY_FIXTURE_VAL_BYTES:-4096}"
separator="<|endoftext|>"
separator_offset="${S1_TINY_FIXTURE_SEPARATOR_OFFSET:-1024}"

mkdir -p "$out_dir"

OUT_DIR="$out_dir" \
FIXTURE_REL_DIR="$fixture_rel_dir" \
MASTER_SEED="$master_seed" \
VAL_SEED_XOR_MASK="$val_seed_xor_mask" \
TRAIN_LEN="$train_len" \
VAL_LEN="$val_len" \
SEPARATOR="$separator" \
SEPARATOR_OFFSET="$separator_offset" \
python3 - <<'PY'
import hashlib
import os
from pathlib import Path

PCG_128_MULTIPLIER = 0x2360_ED05_1FC6_5DA4_4385_DF64_9FCC_F645
SHUFFLE_SEED = 0xDEAD_BEEF

out_dir = Path(os.environ["OUT_DIR"])
fixture_rel_dir = Path(os.environ["FIXTURE_REL_DIR"])
master_seed = int(os.environ["MASTER_SEED"], 0)
val_seed_xor_mask = int(os.environ["VAL_SEED_XOR_MASK"], 0)
train_len = int(os.environ["TRAIN_LEN"], 0)
val_len = int(os.environ["VAL_LEN"], 0)
separator = os.environ["SEPARATOR"].encode("ascii")
separator_offset = int(os.environ["SEPARATOR_OFFSET"], 0)


def sha256(data: bytes) -> str:
    return "sha256:" + hashlib.sha256(data).hexdigest()


def seed128(domain: str, seed: int) -> int:
    digest = hashlib.sha256(f"gbf:s1:{domain}:{seed}".encode("utf-8")).digest()
    return int.from_bytes(digest[:16], "little")


class S1Stream:
    def __init__(self, domain: str, seed: int):
        self.state = seed128(domain, seed) | 1

    def next_u64(self) -> int:
        self.state = (self.state * PCG_128_MULTIPLIER) & ((1 << 128) - 1)
        rot = self.state >> 122
        xsl = ((self.state >> 64) ^ self.state) & ((1 << 64) - 1)
        return ((xsl >> rot) | (xsl << ((64 - rot) & 63))) & ((1 << 64) - 1)


def uniform_u64_inclusive(rng: S1Stream, lo: int, hi: int) -> int:
    if lo > hi:
        raise ValueError("lo must be <= hi")
    range_size = hi - lo + 1
    sample_space = 1 << 64
    acceptance_bound = (sample_space // range_size) * range_size
    while True:
        candidate = rng.next_u64()
        if candidate < acceptance_bound:
            return lo + candidate % range_size


def byte_stream(length: int, seed: int) -> bytearray:
    rng = S1Stream("init", seed)
    return bytearray(uniform_u64_inclusive(rng, 0, 255) for _ in range(length))


def fisher_yates(data: bytes, seed: int) -> bytes:
    values = bytearray(data)
    rng = S1Stream("shuffle", seed)
    for i in range(len(values) - 1, 0, -1):
        j = uniform_u64_inclusive(rng, 0, i)
        values[i], values[j] = values[j], values[i]
    return bytes(values)


if train_len < separator_offset + len(separator):
    raise ValueError("train fixture too short for separator offset")

train = byte_stream(train_len, master_seed)
val = byte_stream(val_len, master_seed ^ val_seed_xor_mask)
train[separator_offset:separator_offset + len(separator)] = separator

train_bytes = bytes(train)
val_bytes = bytes(val)
val_shuffle = fisher_yates(val_bytes, SHUFFLE_SEED)

manifest = f'''schema = "tinystories_manifest.v1"
schema_version = "1.0.0"
corpus_id = "s1-tiny-fixture"
dataset_version = "fixture-v1"
source_name = "synthetic-tiny-fixture"
source_url = "https://example.invalid/gbllm/s1-tiny-fixture"
train_path = "{fixture_rel_dir / "train.bytes"}"
val_path = "{fixture_rel_dir / "val.bytes"}"
train_sha256 = "{sha256(train_bytes)}"
val_sha256 = "{sha256(val_bytes)}"
val_shuffle_deadeef_sha256 = "{sha256(val_shuffle)}"
raw_root = "{fixture_rel_dir}"
raw_byte_policy = "post-decompression bytes; no normalization. The literal ASCII string <|endoftext|> is included once at train byte offset {separator_offset} and is treated as ordinary input bytes."
story_separator = "<|endoftext|>"
s1_policy = "S1 treats this fixture as raw bytes; separator bytes are ordinary input bytes."
deferred_scope = []

[source]
name = "synthetic-tiny-fixture"
url = "https://example.invalid/gbllm/s1-tiny-fixture"
dataset_card_url = "https://example.invalid/gbllm/s1-tiny-fixture-card"
license = "CC0-1.0"
license_url = "https://creativecommons.org/publicdomain/zero/1.0/"
downloaded_at = "2026-05-09"
decompression = "none"

[splits.train]
role = "train"
url = "file://{fixture_rel_dir / "train.bytes"}"
local_filename = "train.bytes"
sha256 = "{sha256(train_bytes)}"
byte_length = {len(train_bytes)}
story_count = 2

[splits.validation]
role = "validation"
url = "file://{fixture_rel_dir / "val.bytes"}"
local_filename = "val.bytes"
sha256 = "{sha256(val_bytes)}"
byte_length = {len(val_bytes)}
story_count = 1
'''

recipe = f'''# S1 Tiny Fixture Corpus

Generated by `scripts/s1_generate_tiny_fixture.sh`.

- master_seed: `{master_seed:#x}`
- validation seed derivation: `master_seed ^ {val_seed_xor_mask:#x}`
- train bytes: `{train_len}`
- validation bytes: `{val_len}`
- RNG stream: F-S1 `InitRng` seed derivation (`seed128("init", seed)`) with rejection-sampled `uniform_u64_inclusive(..., 0, 255)`
- validation shuffle pin: F-S1 `ShuffleRng(0xDEADBEEF)` Fisher-Yates high-to-low loop
- literal separator: `<|endoftext|>`
- separator location: `train.bytes` byte offset `{separator_offset}`

Pinned hashes:

- train_sha256: `{sha256(train_bytes)}`
- val_sha256: `{sha256(val_bytes)}`
- val_shuffle_deadeef_sha256: `{sha256(val_shuffle)}`

This directory is the source of truth for the tiny S1 fixture corpus. Re-running
the generation script with the same seed must reproduce these files byte-for-byte.
'''

(out_dir / "train.bytes").write_bytes(train_bytes)
(out_dir / "val.bytes").write_bytes(val_bytes)
(out_dir / "manifest.toml").write_text(manifest, encoding="utf-8")
(out_dir / "generation_recipe.md").write_text(recipe, encoding="utf-8")

print(f"wrote {out_dir}")
print(f"train_sha256={sha256(train_bytes)}")
print(f"val_sha256={sha256(val_bytes)}")
print(f"val_shuffle_deadeef_sha256={sha256(val_shuffle)}")
PY
