#![forbid(unsafe_code)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command as ProcessCommand;

use clap::{Parser, Subcommand};
use sha2::{Digest, Sha256};

#[derive(Debug, Parser)]
#[command(name = "xtask", color = clap::ColorChoice::Never)]
struct Args {
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    RegenReviewPacket {
        #[arg(long)]
        feature: String,
    },
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    match Args::parse().command {
        Command::RegenReviewPacket { feature } if feature == "F-A8" => regen_f_a8(),
        Command::RegenReviewPacket { feature } => {
            Err(format!("unsupported review packet feature {feature}; expected F-A8").into())
        }
    }
}

fn regen_f_a8() -> Result<(), Box<dyn std::error::Error>> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..");
    let out = root.join("docs/review/f-a8");
    fs::create_dir_all(&out)?;
    let cargo_tree = run_capture(
        &root,
        "cargo",
        &["tree", "-e", "features", "-p", "gbf-debug"],
    )?;
    let cargo_metadata = run_capture(
        &root,
        "cargo",
        &["metadata", "--no-deps", "--format-version", "1"],
    )?;
    let unsafe_report = unsafe_report(&root.join("gbf-debug/src"))?;
    let repro = generate_repro_hashes(&root)?;

    write(
        &out.join("README.md"),
        "# F-A8 Review Packet\n\nThis packet is regenerated by `cargo xtask regen-review-packet --feature F-A8`.\n\n## Reading Order\n\n1. `scope.md` for what lands in this PR and what stays in the follow-up bead.\n2. `source-to-artifact.md` for RFC section-to-code traceability.\n3. `session-wire.md`, `api-surface.md`, and `cli-envelopes.md` for the three externally visible contracts.\n4. `correctness-dossier.md`, `claim-to-gate.md`, and `test-coverage.md` for claim evidence.\n5. `dependency-report.md`, `reproducibility.md`, `generated-artifacts.md`, and `known-debt.md` for audit context.\n6. `reviewer-checklist.md` as the final approval pass.\n\nThe mandatory RFC §14 evidence appears in this directory as named files rather than in one monolithic note, so each row has an owner and a gate.\n",
    )?;
    write(
        &out.join("scope.md"),
        "# Scope\n\nF-A8 ships `gbf-debug`: session files, the rquickjs host, the `gb` object, JSON success/error envelopes, stateless `init`/`exec`/`inspect` CLI commands, the `gbf-debug-usage` skill, and this review packet.\n\nT-A8.8b (`bd-2j4m`) is deliberately left open as a follow-up PR per RFC §11.9 because it depends on committed F-A4/F-A5 runtime ROM fixtures.\n",
    )?;
    write(
        &out.join("architecture.md"),
        "```mermaid\nflowchart LR\n  Agent --> CLI[gbf-debug CLI]\n  CLI --> Session[.gbsess GBSE+zstd+JSON]\n  CLI --> JS[rquickjs host]\n  JS --> GB[gb object]\n  GB --> Emu[gbf-emu]\n  CLI --> ASM[gbf-asm symbols]\n```\n\nThe `.gbsess` byte layout is `GBSE` magic, four zero flag bytes, then a zstd-compressed JSON `Session`.\n",
    )?;
    write(
        &out.join("source-to-artifact.md"),
        "# Source To Artifact Map\n\n| RFC area | Source artifact | Test / evidence |\n|---|---|---|\n| §3.1 session schema | `gbf-debug/src/session.rs` | `cargo test -p gbf-debug --test session_wire session_wire_rejects_bad_container_inputs`; `cargo test -p gbf-debug --test session_wire session_wire_rejects_schema_and_lineage_mismatches`; `session-wire.md` |\n| §3.2 script host determinism | `gbf-debug/src/script.rs` | `cargo test -p gbf-debug --test e2e date_now_and_log_timestamps_are_relative_to_each_exec`; `correctness-dossier.md` |\n| §3.3 `gb` object | `gbf-debug/src/script.rs` | `api-surface.md`; e2e recipe test |\n| §3.4 stateless CLI | `gbf-debug/src/bin/gbf-debug.rs`, `gbf-debug/src/cli.rs` | `cargo test -p gbf-debug --test e2e cli_arg_errors_are_json_exit_one`; `cli-envelopes.md` |\n| §3.6 symbols | `gbf-debug/src/session.rs` | `cargo test -p gbf-debug --test session_wire symbols_sorted_and_ambiguous` |\n| §3.7 skill | `.agents/skills/gbf-debug-usage/` | `cargo test -p gbf-debug --test skill_recipes` |\n| §14 review packet | `xtask/src/main.rs`, `docs/review/f-a8/` | `cargo xtask regen-review-packet --feature F-A8` |\n",
    )?;
    write(
        &out.join("diff-map.md"),
        "# Diff Map\n\n| Path | Risk | Why review it | Gate |\n|---|---:|---|---|\n| `Cargo.toml`, `Cargo.lock`, `.cargo/config.toml` | Medium | Adds the crate, pinned JS/compression deps, and `cargo xtask` alias. | `cargo tree -e features -p gbf-debug` |\n| `gbf-debug/src/session.rs` | High | Defines the durable `.gbsess` wire format and all load-time refusal checks. | `cargo test -p gbf-debug --test session_wire` |\n| `gbf-debug/src/script.rs` | High | Hosts QuickJS, predicate evaluation, the `gb` object, trace exposure, and deterministic stubs. | `cargo test -p gbf-debug --test e2e` |\n| `gbf-debug/src/cli.rs` | High | Owns `init`/`exec`/`inspect` envelopes, deterministic error sessions, timeout partials, and lineage. | `cargo test -p gbf-debug --test e2e deterministic_script_errors_write_normal_error_session` |\n| `gbf-debug/src/bin/gbf-debug.rs` | Medium | Converts clap outcomes into exactly one JSON object on stdout/stderr. | `cargo test -p gbf-debug --test e2e cli_arg_errors_are_json_exit_one` |\n| `.agents/skills/gbf-debug-usage/` | Medium | Teaches future agents the actual CLI surface and determinism rules. | `cargo test -p gbf-debug --test skill_recipes` |\n| `xtask/src/main.rs`, `docs/review/f-a8/` | Medium | Regenerates reviewer evidence and dependency audit artifacts. | `cargo xtask regen-review-packet --feature F-A8` |\n",
    )?;
    write(
        &out.join("session-wire.md"),
        "# Session Wire Evidence\n\nThe on-disk layout is fixed `GBSE` magic, four zero flag bytes, then a zstd-compressed UTF-8 JSON `Session`.\n\nLoad-time hard refusals cover: truncated headers, bad magic, non-zero flags, zstd decode failure, JSON decode failure, schema mismatch, ROM hash mismatch, snapshot ROM mismatch, and unsupported non-PostBootDmg lineage.\n\nThe cross-checks are intentionally redundant: `Session::rom_sha256` pins the embedded `RomBlob`, while `SnapshotLineage::rom_sha256` proves the F-A7 snapshot belongs to the same ROM. Breakpoints/watchpoints persist only `PersistedPredicate::{None,StringifiedSource}`; closure predicates never enter the wire shape.\n",
    )?;
    write(
        &out.join("api-surface.md"),
        "# `gb` API Surface\n\n| Method | Contract | Primary gate |\n|---|---|---|\n| `gb.regs` | Frozen register snapshot; no live mutable reference. | e2e smoke |\n| `gb.read` / `gb.write` | Side-effect-free debugger memory access via F-A7 peek/poke. | e2e smoke |\n| `gb.bus_read` / `gb.bus_write` | Side-effecting host bus operations and trace ingestion. | recipe tests |\n| `gb.step` | Bounded instruction stepping; timeout checked inside long host loops. | e2e smoke |\n| `gb.run_until` | Delegates to F-A7 `run_until_pc`; does not mutate persisted breakpoints. | e2e smoke |\n| `gb.run_until_breakpoint` | Runs until an active trap whose predicate evaluates truthy, budget elapsed, or idle. | predicate e2e regression |\n| `gb.add_breakpoint` / `gb.add_watchpoint` | Persists no-predicate/string predicates; closure predicates are invocation-local with a warning. | predicate e2e regression |\n| `gb.snapshot` / `gb.restore` | In-script transient emulator branch points. | recipe tests |\n| `gb.symbol*` | Embedded symbol table lookup with ambiguity refusal. | session wire tests |\n| `gb.framebuffer`, `gb.input`, `gb.trace_ring`, `gb.clear_trace` | Display/input/trace accessors over F-A7 primitives. | recipe tests |\n",
    )?;
    write(
        &out.join("correctness-dossier.md"),
        "# Correctness Dossier\n\n## Session Schema\n\nTyped enums cover predicate kind, watchpoint kind, and trace event kind. `Session::load_bytes` validates container shape before serde and validates ROM/snapshot lineage after serde.\n\n## JS Host Determinism\n\n`Date.now()` and `log(...).ts_micros_since_script_start` are derived from emulator cycles relative to the current script invocation. `Math.random()` is fixed-seeded. `console` is removed. A QuickJS interrupt handler and bounded Rust host calls enforce liveness without making wall-clock time observable.\n\n## Predicates\n\nString predicates are compiled at registration or startup and evaluated in a restricted scope containing `regs`, `pc`, `access`, `cycle`, `symbol`, and `symbolInBank`. Closure predicates stay in the JS heap under an invocation-local key, see the same temporary predicate scope plus a read-only `gb` view, and are not written to the session.\n\n## CLI\n\nEvery success path writes one JSON object to stdout. Every failure path writes one JSON `ErrorEnvelope` to stderr, including clap parse failures. Deterministic script failures write a normal post-error `session_path`; timeout partials use `partial_session_path` and `determinism: \"nondeterministic_partial\"` only when requested.\n",
    )?;
    write(
        &out.join("claim-to-gate.md"),
        "# Claim To Gate\n\n| Claim | Gate |\n|---|---|\n| Session container rejects bad magic, flags, truncation, zstd decode, JSON decode, schema mismatch, ROM hash mismatch, and snapshot lineage mismatch. | `cargo test -p gbf-debug --test session_wire session_wire_rejects_bad_container_inputs`; `cargo test -p gbf-debug --test session_wire session_wire_rejects_schema_and_lineage_mismatches` |\n| Symbol ambiguity and watchpoint kind contracts are pinned. | `cargo test -p gbf-debug --test session_wire symbols_sorted_and_ambiguous`; `cargo test -p gbf-debug --test session_wire watchpoint_kind_parse_contract` |\n| `init -> exec -> inspect` works over the tiny ROM fixture. | `cargo test -p gbf-debug --test e2e init_exec_inspect_tiny_rom` |\n| String predicates persist and re-evaluate without becoming unconditional. | `cargo test -p gbf-debug --test e2e string_predicate_round_trips_without_becoming_unconditional` |\n| Closure predicates see predicate scope, are invocation-local, and warn. | `cargo test -p gbf-debug --test e2e closure_predicate_is_invocation_local_and_warned` |\n| Deterministic script errors write normal post-error sessions, not timeout partials. | `cargo test -p gbf-debug --test e2e deterministic_script_errors_write_normal_error_session` |\n| CLI arg/help output is structured JSON with RFC exit codes. | `cargo test -p gbf-debug --test e2e cli_arg_errors_are_json_exit_one`; `cargo test -p gbf-debug --test e2e cli_help_is_json_exit_zero` |\n| Virtual time is per script invocation. | `cargo test -p gbf-debug --test e2e date_now_and_log_timestamps_are_relative_to_each_exec` |\n| Skill recipes match the actual CLI/API surface. | `cargo test -p gbf-debug --test skill_recipes` |\n| Dependency feature audit is current. | `cargo tree -e features -p gbf-debug`; see `dependency-tree.txt` |\n| Review packet is reproducible. | `cargo xtask regen-review-packet --feature F-A8` |\n| Workspace integration remains healthy. | pre-commit hook: fmt, clippy, workspace tests |\n",
    )?;
    write(
        &out.join("test-coverage.md"),
        "# Test Coverage\n\nCoverage includes session wire tests, symbol ambiguity tests, output envelope tests, script-host canonicalization tests, recipe execution, predicate persistence regressions, virtual-time regressions, and an `init -> exec -> inspect` e2e smoke over `gbf-emu/tests/fixtures/tiny_rom.gb`.\n\nThe RFC names additional future acceptance filters as design anchors; the executable gates in this PR are the concrete tests listed in `claim-to-gate.md`.\n",
    )?;
    write(
        &out.join("reproducibility.md"),
        &format!(
            "# Reproducibility Report\n\nThe session writer uses fixed `GBSE` magic, zero flags, deterministic serde JSON, and zstd level 3. Runtime host-duration metrics are opt-in and omitted from default envelopes.\n\nHost triple: `{}`\n\nGenerated tiny-ROM fixture evidence:\n\n```\n{}\n```\n",
            std::env::consts::ARCH.to_owned() + "-" + std::env::consts::OS,
            repro
        ),
    )?;
    write(
        &out.join("dependency-report.md"),
        "# Dependency Report\n\nDirect dependencies: `gbf-emu`, `gbf-asm`, `gbf-foundation`, `gbf-abi`, `gbf-hw`, `rquickjs`, `rquickjs-serde`, `zstd`, `base64`, `sha2`, `clap`, `serde`, `serde_json`, `tempfile`. `gameroy-core` enters only through `gbf-emu`.\n\n`rquickjs` is pinned with default features disabled and only `std` enabled. Module loading, loader features, custom allocator features, and async/futures features are not part of the F-A8 surface.\n\nSee `dependency-tree.txt` for `cargo tree -e features -p gbf-debug`.\n",
    )?;
    write(&out.join("dependency-tree.txt"), &cargo_tree)?;
    write(&out.join("cargo-metadata.json"), &cargo_metadata)?;
    write(&out.join("unsafe-grep.txt"), &unsafe_report)?;
    write(
        &out.join("cli-envelopes.md"),
        "# CLI Envelope Shapes\n\n`init`, `exec`, and `inspect` write exactly one JSON object to stdout on success. Argument parse failures and runtime failures write exactly one `ErrorEnvelope` to stderr. `--help` writes one JSON help envelope to stdout with exit code 0.\n\nError envelope command names are `init`, `exec`, `inspect`, or `args` for parse/help failures. Deterministic runtime script failures include the parsed command name and normal `session_path`; timeout partial fields are only set when the user explicitly requested partial timeout writes.\n",
    )?;
    write(
        &out.join("error-shape-report.md"),
        "# Error Shape Report\n\n| Error family | Exit code | JSON `kind` |\n|---|---:|---|\n| Help | 0 | `help` |\n| Clap / CLI argument errors | 1 | `cli_args` |\n| Session load failures | 2 | `session_load` |\n| Session write failures | 3 | `session_write` |\n| Script syntax/runtime/host failures | 4 | `script_syntax`, `script_runtime`, `watchdog_timeout`, `host_binding` |\n| Predicate compile failures | 5 | `predicate_compile` |\n| Emulator / I/O / post-load PC failures | 6 | `io` or `post_load_pc` |\n| Symbol hydration failures | 7 | `symbol_hydration` |\n",
    )?;
    write(
        &out.join("generated-artifacts.md"),
        "# Generated Artifacts\n\n`cargo xtask regen-review-packet --feature F-A8` writes this directory, `dependency-tree.txt`, `cargo-metadata.json`, `unsafe-grep.txt`, and reproducibility hashes generated from an `init -> exec` tiny-ROM session pair.\n\nNo checked-in `.gbsess` binary fixture is required for F-A8; the deterministic session bytes are regenerated into a temp directory and recorded by hash in `reproducibility.md`.\n",
    )?;
    write(
        &out.join("known-debt.md"),
        "# Known Debt And Out Of Scope\n\n| Item | Owner / removal condition |\n|---|---|\n| Build identity decode | Follow-up once F-A5 emits a `BuildIdentityBlock`. |\n| `gb.harness.send(op)` | F-D2 harness control-plane bead. |\n| `inspect --full` | Optional ergonomics bead after M0. |\n| `gb.disable_breakpoint(addr)` | Optional non-breaking API addition; schema already has `enabled`. |\n| T-A8.8b runtime-ASM conformance smoke suite | `bd-2j4m`, follow-up PR after F-A4/F-A5 fixtures exist. |\n",
    )?;
    write(
        &out.join("out-of-scope.md"),
        "# Out Of Scope\n\nThe PR does not add a REPL, daemon, persistent JS context, session auto-migration, `gbf-store` integration, typed runtime identity decoding, harness operations, GBC features, or the T-A8.8b runtime-ASM conformance suite.\n",
    )?;
    write(
        &out.join("reviewer-checklist.md"),
        "- [ ] Session rejects bad magic/flags/schema/hash/lineage.\n- [ ] CLI emits one JSON object on success/failure.\n- [ ] `gb.read` and `gb.bus_read` remain separate.\n- [ ] Closure predicates warn and do not persist.\n- [ ] Skill docs match the actual CLI surface.\n- [ ] No `unsafe` in `gbf-debug/src`.\n",
    )?;
    Ok(())
}

fn write(path: &Path, contents: &str) -> Result<(), Box<dyn std::error::Error>> {
    fs::write(path, contents)?;
    Ok(())
}

fn run_capture(
    cwd: &Path,
    program: &str,
    args: &[&str],
) -> Result<String, Box<dyn std::error::Error>> {
    let output = ProcessCommand::new(program)
        .args(args)
        .current_dir(cwd)
        .output()?;
    if !output.status.success() {
        return Err(format!(
            "{program} {} failed with status {}:\n{}",
            args.join(" "),
            output.status,
            String::from_utf8_lossy(&output.stderr)
        )
        .into());
    }
    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

fn generate_repro_hashes(root: &Path) -> Result<String, Box<dyn std::error::Error>> {
    let dir = std::env::temp_dir().join(format!("gbf-debug-f-a8-review-{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir)?;
    let s0 = dir.join("s0.gbsess");
    let s1 = dir.join("s1.gbsess");
    let script = dir.join("script.js");
    fs::write(
        &script,
        "gb.step(1);\nglobalThis.result = { pc: gb.regs.pc };\n",
    )?;
    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".to_owned());
    let init_out = ProcessCommand::new(&cargo)
        .current_dir(root)
        .args([
            "run",
            "-q",
            "-p",
            "gbf-debug",
            "--",
            "init",
            "--rom",
            root.join("gbf-emu/tests/fixtures/tiny_rom.gb")
                .to_str()
                .ok_or("non-utf8 rom path")?,
            "--sym",
            root.join("docs/review/f-a1/artifacts/tiny_rom.sym")
                .to_str()
                .ok_or("non-utf8 sym path")?,
            "--out",
            s0.to_str().ok_or("non-utf8 session path")?,
        ])
        .output()?;
    if !init_out.status.success() {
        return Err(format!(
            "gbf-debug init failed:\n{}",
            String::from_utf8_lossy(&init_out.stderr)
        )
        .into());
    }
    let exec_out = ProcessCommand::new(&cargo)
        .current_dir(root)
        .args([
            "run",
            "-q",
            "-p",
            "gbf-debug",
            "--",
            "exec",
            "--in",
            s0.to_str().ok_or("non-utf8 input session path")?,
            "--script",
            script.to_str().ok_or("non-utf8 script path")?,
            "--out",
            s1.to_str().ok_or("non-utf8 output session path")?,
        ])
        .output()?;
    if !exec_out.status.success() {
        return Err(format!(
            "gbf-debug exec failed:\n{}",
            String::from_utf8_lossy(&exec_out.stderr)
        )
        .into());
    }
    let temp_prefix = dir.to_string_lossy();
    let init_stdout = String::from_utf8_lossy(&init_out.stdout)
        .replace(temp_prefix.as_ref(), "$TMP/gbf-debug-f-a8-review");
    let exec_stdout = String::from_utf8_lossy(&exec_out.stdout)
        .replace(temp_prefix.as_ref(), "$TMP/gbf-debug-f-a8-review");
    let report = format!(
        "init stdout: {}\nexec stdout: {}\ns0.gbsess sha256: {}\ns1.gbsess sha256: {}",
        init_stdout.trim(),
        exec_stdout.trim(),
        sha256_hex(&fs::read(&s0)?),
        sha256_hex(&fs::read(&s1)?)
    );
    let _ = fs::remove_dir_all(&dir);
    Ok(report)
}

fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    digest.iter().map(|byte| format!("{byte:02x}")).collect()
}

fn unsafe_report(src: &Path) -> Result<String, Box<dyn std::error::Error>> {
    let mut findings = Vec::new();
    for path in rust_files(src)? {
        let text = fs::read_to_string(&path)?;
        for (idx, line) in text.lines().enumerate() {
            let trimmed = line.trim();
            if trimmed.starts_with("unsafe ")
                || trimmed.contains(" unsafe ")
                || trimmed.contains("unsafe{")
                || trimmed.contains("unsafe {")
            {
                findings.push(format!(
                    "{}:{}: {}",
                    path.strip_prefix(src)?.display(),
                    idx + 1,
                    trimmed
                ));
            }
        }
    }
    if findings.is_empty() {
        Ok("No unsafe blocks or unsafe functions found under gbf-debug/src.\n".to_owned())
    } else {
        Ok(findings.join("\n") + "\n")
    }
}

fn rust_files(root: &Path) -> Result<Vec<PathBuf>, Box<dyn std::error::Error>> {
    let mut out = Vec::new();
    for entry in fs::read_dir(root)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            out.extend(rust_files(&path)?);
        } else if path.extension().and_then(|ext| ext.to_str()) == Some("rs") {
            out.push(path);
        }
    }
    out.sort();
    Ok(out)
}
