//! Deployed-model generation regression gate.
//!
//! The **committed real d192 distilled student** (`D192_REAL_EXPORT_DIR`, the
//! exact checkpoint the shipped `gbllm-shell-d192.gb` is built from) must keep
//! reproducing the host integer evaluator **byte-exactly** on-device, both for
//! a single forward pass (one-token ROM) and for sustained autoregressive
//! generation (multi-token ROM: state carried in WRAM, argmax fed back).
//!
//! This is the safety net for kernel *speed* work: any change to the ROM
//! codegen that alters a single generated byte fails here. Kept small so it is
//! a fast, routinely-runnable guard rather than a full evidence sweep — the
//! `d192-real` bench bin remains the exhaustive fidelity runner.
//!
//! Read-only: nothing under `experiments/` is written.

use std::path::PathBuf;

use gbf_bench::d192_real::D192_REAL_EXPORT_DIR;
use gbf_bench::stateful::{load_state_checkpoint, run_state_rom_gate, run_state_seed_generation};
use gbf_kernel::asm_impl_state::build_state_multi_token_rom;
use gbf_kernel::state_model_ref::{IntStateLoweredModel, StateTopology};

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("workspace root")
        .to_path_buf()
}

/// Small enough to run in well under a minute; long enough to carry state
/// across several steps, feed argmax back, and exercise the full per-token
/// path (norm, state in/out projections, decay, FFN, head) repeatedly.
const N_TOKENS: u16 = 12;

#[test]
fn deployed_d192_generation_stays_byte_exact_on_device() {
    let export_dir = repo_root().join(D192_REAL_EXPORT_DIR);
    if !export_dir.join("manifest.json").exists() {
        eprintln!("committed d192 export missing; skipping (fresh clone without experiments)");
        return;
    }

    let bundle = load_state_checkpoint(&export_dir).expect("loads via manifest topology");
    assert_eq!(
        bundle.topology,
        StateTopology::D192,
        "deployed topology is d192"
    );
    let lowered = IntStateLoweredModel::lower(&bundle.checkpoint).expect("lowers");

    // --- one-token ROM: zero state + a carried (warmed-up) state ---
    let mut state = lowered.zero_state();
    let t0 = lowered.forward(75, &mut state);
    let _ = lowered.forward(t0.argmax, &mut state);
    let cases = vec![
        (0usize, 75u8, lowered.zero_state()),
        (2usize, t0.argmax, state),
    ];
    let report = run_state_rom_gate(&lowered, &cases).expect("one-token gate runs");
    assert!(
        report.all_byte_exact,
        "deployed d192 one-token forward diverged from the host evaluator: {:?}",
        report
            .runs
            .iter()
            .flat_map(|r| r.mismatches.iter())
            .collect::<Vec<_>>()
    );

    // --- multi-token ROM: sustained on-device generation, argmax fed back ---
    let rom = build_state_multi_token_rom(&lowered, N_TOKENS).expect("multi-token ROM builds");
    for seed in [19u8, 75u8] {
        let run = run_state_seed_generation(&rom, &lowered, seed).expect("seed generation runs");
        assert!(
            run.sequences_match,
            "seed 0x{seed:02X}: on-device generation diverged from host at index {:?}\n\
             host sha256 {} vs rom sha256 {}",
            run.first_divergence_index, run.host_sequence_sha256, run.rom_sequence_sha256,
        );
        assert!(
            run.all_checks_pass(),
            "seed 0x{seed:02X}: on-device health/dumps regressed: \
             first_dumps={} last_dumps={} sp_home={} wram_clean={} done={}",
            run.first_token_checkpoints_byte_exact,
            run.last_token_checkpoints_byte_exact,
            run.sp_home_every_token,
            run.wram_untouched_regions_ok,
            run.done_flag_set,
        );
    }
}
