#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$ROOT"

RFC="history/rfcs/F-S7-moe-beats-dense.md"
ARTIFACT_SCHEMA="gbf-artifact/src/s7_schema.rs"
DISTILL_HELPER="gbf-train/src/loss/distillation.rs"
SCHEMA_TEST="gbf-experiments/tests/s7_schema_discipline.rs"
S7_CLI="gbf-experiments/src/s7/cli.rs"
S7_SCHEMA="gbf-experiments/src/s7/schema.rs"
S7_RUN="gbf-experiments/src/s7/run.rs"
S7_SUMMARIES="gbf-experiments/src/s7/summaries.rs"
S7_COMPARISON="gbf-experiments/src/s7/comparison.rs"
S7_FRONTIER="gbf-experiments/src/s7/frontier.rs"
S7_SUPPORT_ARTIFACTS="gbf-experiments/src/s7/support_artifacts.rs"
S7_BURN_GRAD_SMOKE="gbf-experiments/src/s7/burn_grad_smoke.rs"
S7_CLI_TEST="gbf-cli/tests/s7_cli_s7.rs"
S7_CLOSURE_PACKET="gbf-experiments/src/s7/closure_packet.rs"
ISOLATION_SCRIPT="scripts/s7_isolation_check.sh"
PREREG_SCRIPT="scripts/s7_preregistration_check.sh"
PREREG_PIN_SCRIPT="scripts/s7_preregistration_pin.sh"
VERIFY_PACKET_SCRIPT="scripts/review/f-s7/verify-packet.sh"
S7_PR_WORKFLOW=".github/workflows/s7-pr.yml"
REPORT_VALIDATOR="scripts/review/f-s7/validate-report.py"
REPORT_EMITTER="scripts/review/f-s7/emit-report.py"
ARTIFACT_VALIDATOR="scripts/review/f-s7/validate-artifacts.py"
REVIEW_VALIDATOR="scripts/review/f-s7/validate-reviews.py"
PACKET_ASSEMBLER="scripts/review/f-s7/assemble-packet.py"
ACPX_REVIEW_RUNNER="scripts/review/f-s7/run-acpx-reviews.py"
BEAD_REVIEW_AUDITOR="scripts/review/f-s7/audit-bead-reviews.py"
CLOSURE_DEP_AUDITOR="scripts/review/f-s7/audit-closure-deps.py"
S7_RUN_ACPX_TEST="scripts/tests/s7_run_acpx_reviews_test.sh"
S7_AUDIT_BEAD_REVIEWS_TEST="scripts/tests/s7_audit_bead_reviews_test.sh"
S7_AUDIT_CLOSURE_DEPS_TEST="scripts/tests/s7_audit_closure_deps_test.sh"

require_present() {
  local pattern="$1"
  shift
  if ! rg -n -- "$pattern" "$@" >/dev/null; then
    echo "schema discipline failed: missing pattern '$pattern' in $*" >&2
    exit 1
  fi
}

require_absent() {
  local pattern="$1"
  shift
  if rg -n -- "$pattern" "$@" >/dev/null; then
    echo "schema discipline failed: stale pattern '$pattern' found in $*" >&2
    rg -n -- "$pattern" "$@" >&2
    exit 1
  fi
}

require_absent 's7_moe_vs_dense\.v1' "$RFC" "$ARTIFACT_SCHEMA" gbf-experiments scripts
require_absent '--topology MoeTiny,MoeTinyDenseMatched' "$RFC" "$ISOLATION_SCRIPT"
require_absent 's6_tolerance' "$RFC"
require_absent 'byte_length\(val_bytes\)' "$RFC"
require_absent 'distill_loss_raw:[[:space:]]+LossNatsPerByte' "$RFC"

require_present '## 13\.6 s7_dense_vs_moe\.v1' "$RFC"
require_present 'schema:[[:space:]]+"s7_dense_vs_moe\.v1"' "$RFC"
require_present 'cargo run --release -p gbf-cli --features s7-moe -- s7 replay' "$RFC"
require_present 'cargo run --release -p gbf-cli --features s7-dense-matched -- s7 replay' "$RFC"
require_present 'scripts/s7_isolation_check\.sh --self-test' "$RFC"

require_present 'distill_loss_raw:[[:space:]]+DistillRawDiagnostic' "$RFC"
require_present 'DistillRawDiagnostic :=' "$RFC"
require_present 'NotAvailable \{ reason: "no_frozen_teacher", phase: TrainPhase \}' "$RFC"
require_present 'represented as DistillRawDiagnostic::NotAvailable, never as 0\.0\.' "$RFC"

require_present 'input:[[:space:]]+raw_router_logits: Tensor\[batch, seq, n_experts\]' "$RFC"
require_present 'effective_logits:[[:space:]]+Tensor\[batch, seq, n_experts\]' "$RFC"
require_present 'router_z_loss\(raw_router_logits\)' "$RFC"
require_present '∂ z_loss / ∂ raw_router_logits z' "$RFC"

require_present 'TransitionEntry :=' "$RFC"
require_present 'from_expert: ExpertId' "$RFC"
require_present 'to_expert:[[:space:]]+ExpertId' "$RFC"
require_present '\(from_expert, to_expert\) pair' "$RFC"
require_present 'TSD-5[[:space:]]+from_expert and to_expert are directional' "$RFC"
require_present 'LayerId[[:space:]]+:= u8[[:space:]]+; 0\.\.n_blocks-1' "$RFC"
require_present 'EPD-4[[:space:]]+expert_id values exhaust 0\.\.n_experts-1' "$RFC"

require_present 'grad_norms:[[:space:]]+List\[\(TrainStep, GradNormSummary\)\]' "$RFC"
require_present 'RL-Length[[:space:]]+If completion = Completed:' "$RFC"
require_present 'RL-Eval[[:space:]]+If completion = Completed:' "$RFC"
require_present 'S-Tokens[[:space:]]+token_count = length\(charset_v1_encode\(normalize\(val_bytes\)\)\)' "$RFC"

require_present 'pub enum DistillRawDiagnostic' "$ARTIFACT_SCHEMA" "$DISTILL_HELPER"
require_present 'DistillRawDiagnostic::NotAvailable' "$DISTILL_HELPER" "$ARTIFACT_SCHEMA"
require_present 'DistillRawDiagnostic::Value' "$DISTILL_HELPER"
require_present 'pub struct TransitionEntry' "$ARTIFACT_SCHEMA"
require_present 'pub from_expert: ExpertId' "$ARTIFACT_SCHEMA"
require_present 'pub to_expert: ExpertId' "$ARTIFACT_SCHEMA"
require_present 'DuplicateTransitionEntry' "$ARTIFACT_SCHEMA"
require_present 'pub grad_norms: Vec<\(u64, GradNormSummary\)>' "$ARTIFACT_SCHEMA"
require_present 'score_report_token_count_uses_charset_v1_normalized_length' "$SCHEMA_TEST"
require_present 's7_isolation_script_pins_split_replay_order' "$SCHEMA_TEST"
require_present 's7_cli_surface_names_replay_materialization_and_report_emission' "$SCHEMA_TEST"
require_present 's7_artifact_validator_python_canonical_hash_matches_rust_foundation' "$SCHEMA_TEST"
require_present 'MaterializeRun\(S7MaterializeRunArgs\)' "$S7_CLI"
require_present 'DeriveSummaries\(S7DeriveSummariesArgs\)' "$S7_CLI"
require_present 'DeriveComparison\(S7DeriveComparisonArgs\)' "$S7_CLI"
require_present 'DeriveFrontier\(S7DeriveFrontierArgs\)' "$S7_CLI"
require_present 'MaterializeSupportArtifact\(S7MaterializeSupportArtifactArgs\)' "$S7_CLI"
require_present 'OracleRouted\(S7OracleRoutedArgs\)' "$S7_CLI"
require_present 'EmulatorOneToken\(S7EmulatorOneTokenArgs\)' "$S7_CLI"
require_present 'BurnGradSmoke\(S7BurnGradSmokeArgs\)' "$S7_CLI"
require_present 'gbf s7 materialize-run' "$S7_CLI"
require_present 'gbf s7 derive-summaries' "$S7_CLI"
require_present 'gbf s7 derive-comparison' "$S7_CLI"
require_present 'gbf s7 derive-frontier' "$S7_CLI"
require_present 'gbf s7 materialize-support-artifact' "$S7_CLI"
require_present 'gbf s7 oracle-routed' "$S7_CLI"
require_present 'gbf s7 emulator-one-token' "$S7_CLI"
require_present 'gbf s7 burn-grad-smoke' "$S7_CLI"
require_present 'materialize_completed_run_artifacts' "$S7_CLI" "$S7_RUN"
require_present 'materialize_s7_summaries' "$S7_CLI" "$S7_SUMMARIES"
require_present 'materialize_dense_vs_moe_comparison' "$S7_CLI" "$S7_COMPARISON"
require_present 'materialize_s7_frontier' "$S7_CLI" "$S7_FRONTIER"
require_present 'materialize_support_artifact' "$S7_CLI" "$S7_SUPPORT_ARTIFACTS"
require_present 'compare_with_artifact_oracle_trace' "$S7_CLI" "gbf-experiments/src/s7/emulator_one_token.rs"
require_present 'produce_burn_grad_smoke_artifact' "$S7_CLI" "$S7_BURN_GRAD_SMOKE"
require_present 'OracleRoutedReport' "$S7_SCHEMA"
require_present 'OracleRouteCoverage' "$S7_SCHEMA"
require_present 'QuantSpec::weight_quant' "$S7_SCHEMA" "$S7_SUPPORT_ARTIFACTS" "$ARTIFACT_VALIDATOR"
require_present 'S7RunMaterializeError' "$S7_RUN"
require_present 'S7SummaryMaterializeError' "$S7_SUMMARIES"
require_present 'S7ComparisonMaterializeError' "$S7_COMPARISON"
require_present 'S7FrontierMaterializeError' "$S7_FRONTIER"
require_present 'S7SupportArtifactMaterializeError' "$S7_SUPPORT_ARTIFACTS"
require_present 'S7SupportArtifactKind' "$S7_SUPPORT_ARTIFACTS"
require_present 's7_switch_stats\.v1' "$S7_SUPPORT_ARTIFACTS"
require_present 'switch-stats' "$S7_CLI" "$S7_SUPPORT_ARTIFACTS"
require_present 'MissingSeed' "$S7_SUPPORT_ARTIFACTS"
require_present 'validate_switch_stats' "$S7_SUPPORT_ARTIFACTS"
require_present 's7_router_collapse_sweep\.v1' "$S7_SUPPORT_ARTIFACTS"
require_present 's7_lambda_switch_sweep_step\.v1' "$S7_SUPPORT_ARTIFACTS"
require_present 'production_closure_retrain_score' "$RFC" "$S7_SUPPORT_ARTIFACTS" "$ARTIFACT_VALIDATOR" "$S7_CLI_TEST"
require_present 'producer_kind' "$RFC" "$S7_SUPPORT_ARTIFACTS" "$ARTIFACT_VALIDATOR" "$S7_CLI_TEST"
require_present 'router-collapse-sweep' "$S7_CLI" "$S7_SUPPORT_ARTIFACTS"
require_present 'validate_router_collapse_sweep' "$S7_SUPPORT_ARTIFACTS"
require_present 's7_frontier\.v1' "$S7_SUPPORT_ARTIFACTS"
require_present 's7_burn_grad_smoke\.v1' "$S7_SUPPORT_ARTIFACTS"
require_present 'fixture_seed' "$S7_SUPPORT_ARTIFACTS" "$ARTIFACT_VALIDATOR" "$S7_BURN_GRAD_SMOKE" "$RFC"
require_present 'burn_adapter_version' "$S7_SUPPORT_ARTIFACTS" "$ARTIFACT_VALIDATOR" "$S7_BURN_GRAD_SMOKE" "$RFC"
require_present 'supported_clipped_activation_count' "$S7_SUPPORT_ARTIFACTS" "$ARTIFACT_VALIDATOR" "$RFC"
require_present 'learned_activation_range_unsupported' "$S7_SUPPORT_ARTIFACTS" "$ARTIFACT_VALIDATOR" "$RFC"
require_present 'projection_biases_unsupported' "$S7_SUPPORT_ARTIFACTS" "$ARTIFACT_VALIDATOR" "$RFC"
require_present 'ExpertBlockQat bias and learned activation-range parameters are rejected' "$S7_SUPPORT_ARTIFACTS" "$ARTIFACT_VALIDATOR"
require_present 's7_oracle_routed\.v1' "$S7_SUPPORT_ARTIFACTS"
require_present 's7_emulator_one_token\.v1' "$S7_SUPPORT_ARTIFACTS"
require_present 's7_materialize_run_writes_completed_artifact_paths' "$S7_CLI_TEST"
require_present 's7_materialize_run_rejects_incomplete_fixture_shaped_run_log' "$S7_CLI_TEST"
require_present 's7_derive_summaries_writes_comparison_summary_inputs' "$S7_CLI_TEST"
require_present 's7_derive_summaries_rejects_missing_switch_stats_seed' "$S7_CLI_TEST"
require_present 's7_derive_comparison_writes_dense_vs_moe_artifact' "$S7_CLI_TEST"
require_present 's7_derive_comparison_rejects_missing_materialized_score' "$S7_CLI_TEST"
require_present 's7_derive_frontier_writes_frontier_artifact' "$S7_CLI_TEST"
require_present 's7_derive_frontier_rejects_bad_per_block_total' "$S7_CLI_TEST"
require_present 's7_oracle_routed_writes_h9_report' "$S7_CLI_TEST"
require_present 's7_oracle_routed_rejects_over_tolerance_logits' "$S7_CLI_TEST"
require_present 's7_oracle_routed_rejects_missing_route_coverage_axis' "$S7_CLI_TEST"
require_present 's7_emulator_one_token_writes_h10_report' "$S7_CLI_TEST"
require_present 's7_emulator_one_token_rejects_over_tolerance_logits' "$S7_CLI_TEST"
require_present 's7_burn_grad_smoke_writes_h8_fixture_report' "$S7_CLI_TEST"
require_present 's7_materialize_support_artifact_writes_frontier_packet_path' "$S7_CLI_TEST"
require_present 's7_materialize_support_artifact_rejects_self_hash_mismatch' "$S7_CLI_TEST"
require_present 's7_materialize_support_artifact_writes_burn_grad_packet_path' "$S7_CLI_TEST"
require_present 's7_materialize_support_artifact_rejects_burn_grad_bias_gradient_fields' "$S7_CLI_TEST"
require_present 's7_materialize_support_artifact_writes_switch_stats_packet_path' "$S7_CLI_TEST"
require_present 's7_materialize_support_artifact_rejects_switch_stats_seed_mismatch' "$S7_CLI_TEST"
require_present 's7_materialize_support_artifact_writes_router_collapse_sweep_packet_path' "$S7_CLI_TEST"
require_present 's7_materialize_support_artifact_rejects_router_collapse_sweep_record_hash_mismatch' "$S7_CLI_TEST"
require_present 's7_materialize_support_artifact_requires_emulator_topology' "$S7_CLI_TEST"
require_present 'validate_s7_closure' "$S7_CLOSURE_PACKET"
require_present 'S7ClosureValidationInput' "$S7_CLOSURE_PACKET"
require_present 'S7SwitchStatsBundleManifest' "$S7_CLOSURE_PACKET"
require_present 'S7SwitchStatsReport' "$S7_CLOSURE_PACKET"
require_present 'seed_bundle_self_hashes' "$S7_CLOSURE_PACKET"
require_present 'S7ReportMarkdown' "$S7_CLOSURE_PACKET"
require_present 'normalize_report_for_hash' "$S7_CLOSURE_PACKET"
require_present 'validate_matched_bytes_hash' "$S7_CLOSURE_PACKET"
require_present 'matched_bytes_self_hash' "$S7_CLOSURE_PACKET"
require_present 'validate_actual_run_completed' "$S7_CLOSURE_PACKET"
require_present 'actual run-log completion is not completed' "$S7_CLOSURE_PACKET"
require_present 'validate_actual_artifact_identity' "$S7_CLOSURE_PACKET"
require_present 'topology mismatch' "$S7_CLOSURE_PACKET"
require_present 'seed mismatch' "$S7_CLOSURE_PACKET"
require_present 'validate_outcome_comparison_alignment' "$S7_CLOSURE_PACKET"
require_present 'PassClean outcome conflicts' "$S7_CLOSURE_PACKET"
require_present 'FailParity outcome requires' "$S7_CLOSURE_PACKET"
require_present 'verified_self_hash' "$S7_CLOSURE_PACKET"
require_present 'expected_schema' "$S7_CLOSURE_PACKET"
require_present 'schema must be' "$S7_CLOSURE_PACKET"
require_present 'must use canonical JSON bytes' "$S7_CLOSURE_PACKET"
require_present 'duplicate JSON key' "$S7_CLOSURE_PACKET"
require_present 'unsupported YAML anchor/alias' "$S7_CLOSURE_PACKET"
require_present 'unsupported YAML block scalar' "$S7_CLOSURE_PACKET"
require_present 'unsupported YAML flow collection' "$S7_CLOSURE_PACKET"
require_present 'S7RunLog' "$S7_CLOSURE_PACKET"
require_present 'S7ScoreReport' "$S7_CLOSURE_PACKET"
require_present 'S7DenseVsMoeComparisonReport' "$S7_CLOSURE_PACKET"
require_present 'RouterCollapseSweepReport' "$S7_CLOSURE_PACKET"
require_present 'S7FrontierReport' "$S7_CLOSURE_PACKET"
require_present 'S7BurnGradSmokeReport' "$S7_CLOSURE_PACKET"
require_present 'S7OracleRoutedReport' "$S7_CLOSURE_PACKET"
require_present 'EmulatorOneTokenReport' "$S7_CLOSURE_PACKET"
require_present 'invalid \{label\} self-hash' "$S7_CLOSURE_PACKET"
require_present '"s7_run_log"' "$S7_CLOSURE_PACKET"
require_present '"s7_score"' "$S7_CLOSURE_PACKET"
require_present '"s7_switch_stats_bundle"' "$S7_CLOSURE_PACKET"
require_present '"s7_dense_vs_moe"' "$S7_CLOSURE_PACKET"
require_present '"s7_router_collapse_sweep"' "$S7_CLOSURE_PACKET"
require_present '"s7_frontier"' "$S7_CLOSURE_PACKET"
require_present '"s7_burn_grad_smoke"' "$S7_CLOSURE_PACKET"
require_present '"s7_oracle_routed"' "$S7_CLOSURE_PACKET"
require_present '"s7_emulator_one_token"' "$S7_CLOSURE_PACKET"
require_present 'S7_REQUIRED_REPORT_HASH_FIELDS' "$S7_CLOSURE_PACKET"
require_present 'validate_report_scalars' "$S7_CLOSURE_PACKET"
require_present 'schema must be \\"s7_report\.v1\\"' "$S7_CLOSURE_PACKET"
require_present 'decision must be ProceedToS8 or ProceedToS8DenseOnly' "$S7_CLOSURE_PACKET"
require_present 'rfc_revision must be a git commit id or sha256 hash' "$S7_CLOSURE_PACKET"
require_present '\.scalar\("emulator_one_token_dense_self_hash"\)' "$S7_CLOSURE_PACKET"
require_present 'S7_REQUIRED_REPORT_BODY_HEADINGS' "$S7_CLOSURE_PACKET"
require_present 'S7_REQUIRED_HYPOTHESIS_VERDICTS' "$S7_CLOSURE_PACKET"
require_present 'missing body heading' "$S7_CLOSURE_PACKET"
require_present 'missing explicit \{hypothesis\} hypothesis verdict' "$S7_CLOSURE_PACKET"
require_present 'closure-candidate reports must not use NotEvaluatedDueToPriorGate' "$S7_CLOSURE_PACKET"
require_present 'validate_report_rows' "$S7_CLOSURE_PACKET"
require_present 'per_seed_artifacts must contain 10 rows' "$S7_CLOSURE_PACKET"
require_present 'duplicate per_seed_artifacts row' "$S7_CLOSURE_PACKET"
require_present '## Reproducibility statement' "$S7_CLOSURE_PACKET"
require_present 's7_preregistration_check' "$PREREG_SCRIPT"
require_present 'validate_pass_version' "$PREREG_SCRIPT"
require_present 'pass_version_S7 must be finalized' "$PREREG_SCRIPT"
require_present 'pass_version_S7 must be semver or an s7-\* final pin id' "$PREREG_SCRIPT"
require_present 'matched_bytes_self_hash' "$PREREG_SCRIPT"
require_present 'experiments/S7/smoke' "$PREREG_SCRIPT"
require_present 'predictions_commit must be an ancestor of HEAD/current checkout' "$PREREG_SCRIPT"
require_present 'rfc_revision must be an ancestor of HEAD/current checkout' "$PREREG_SCRIPT"
require_present 'first_result_commit is unset but S7 result evidence exists' "$PREREG_SCRIPT"
require_present 'first_result_commit is not the earliest S7 result artifact commit' "$PREREG_SCRIPT"
require_present 'Emit fixtures/preregistration/s7\.toml' "$PREREG_PIN_SCRIPT"
require_present 'current RFC predictions section differs from predictions_commit' "$PREREG_PIN_SCRIPT"
require_present 'current RFC prediction heading line range differs from predictions_commit' "$PREREG_PIN_SCRIPT"
require_present '--check-ready' "$PREREG_PIN_SCRIPT" "$VERIFY_PACKET_SCRIPT"
require_present 'predictions_commit must be an ancestor of HEAD/current checkout' "$PREREG_PIN_SCRIPT"
require_present 'S7 verify-packet: NEEDS_CHANGES' "$VERIFY_PACKET_SCRIPT"
require_present 'S7 preregistration pin readiness failed' "$VERIFY_PACKET_SCRIPT"
require_present 'requires clean git worktree before review/head validation' "$VERIFY_PACKET_SCRIPT" "scripts/tests/s7_verify_packet_test.sh"
require_absent 'missing required section/pattern' "$VERIFY_PACKET_SCRIPT"
require_absent 'dense emulator one-token result required by DenseOnly decision' "$VERIFY_PACKET_SCRIPT"
require_present 'verify-packet\.sh --substrate-only' "$S7_PR_WORKFLOW"
require_present 's7_verify_packet_test\.sh' "$S7_PR_WORKFLOW"
require_present 's7_preregistration_check_test\.sh' "$S7_PR_WORKFLOW"
require_present 's7_preregistration_pin_test\.sh' "$S7_PR_WORKFLOW"
require_present 's7_validate_artifacts_test\.sh' "$S7_PR_WORKFLOW"
require_present 's7_validate_report_test\.sh' "$S7_PR_WORKFLOW"
require_present 's7_validate_reviews_test\.sh' "$S7_PR_WORKFLOW"
require_present 's7_audit_bead_reviews_test\.sh' "$S7_PR_WORKFLOW"
require_present 's7_audit_closure_deps_test\.sh' "$S7_PR_WORKFLOW"
require_present 's7_assemble_packet_test\.sh' "$S7_PR_WORKFLOW"
require_present 's7_run_acpx_reviews_test\.sh' "$S7_PR_WORKFLOW"
require_present 'actions/upload-artifact@v4' "$S7_PR_WORKFLOW"
require_present 's7 validate-closure' "$VERIFY_PACKET_SCRIPT"
require_present 'S7 Rust closure validation failed' "$VERIFY_PACKET_SCRIPT"
require_present 'synthetic S7 CLI feature preflight self-test' "$VERIFY_PACKET_SCRIPT"
require_present 'synthetic Rust closure gate self-test' "$VERIFY_PACKET_SCRIPT"
require_present 'experiments/S7/dense-vs-moe/comparison\.json' "$VERIFY_PACKET_SCRIPT"
require_present 'docs/experiments/S7-report\.md' "$VERIFY_PACKET_SCRIPT"
require_present 'scripts/review/f-s7/assemble-packet.py --manifest <production-bundle-manifest.json> --run-reviews' "$VERIFY_PACKET_SCRIPT"
require_present 'sudo apt-get install -y ripgrep' "$S7_PR_WORKFLOW"
require_present 'Build a fail-closed F-S7 s7_report\.v1 from production artifacts' "$REPORT_EMITTER"
require_present 'generated_at and report_self_hash nulled' "$REPORT_VALIDATOR"
require_present 'S7 report closure shape: NEEDS_CHANGES' "$REPORT_VALIDATOR"
require_present 'per_seed_artifacts must contain 10 rows' "$REPORT_VALIDATOR"
require_present 'ProceedToS8DenseOnly is permitted only when s7_outcome is FailParity' "$REPORT_VALIDATOR"
require_present 'Decision body must match front matter decision' "$REPORT_VALIDATOR"
require_present 'body_section' "$REPORT_VALIDATOR"
require_present 'unsupported YAML flow collection' "$REPORT_VALIDATOR"
require_present 'duplicate front matter field' "$REPORT_VALIDATOR"
require_present 'report artifact reference has duplicate JSON key' "$REPORT_VALIDATOR"
require_present 'report artifact reference must use canonical JSON bytes' "$REPORT_VALIDATOR"
require_present 'report artifact reference has non-canonical JSON value' "$REPORT_VALIDATOR"
require_present 'must match artifact self-hash' "$REPORT_VALIDATOR"
require_present 'checkpoint_self_hash' "$REPORT_VALIDATOR"
require_present 'switch_stats_self_hash' "$REPORT_VALIDATOR"
require_present 'report_self_hash must match report bytes' "$REPORT_VALIDATOR"
require_present 'S7 artifact closure shape: NEEDS_CHANGES' "$ARTIFACT_VALIDATOR"
require_present 'must use canonical JSON bytes' "$ARTIFACT_VALIDATOR"
require_present 'duplicate JSON key' "$ARTIFACT_VALIDATOR"
require_present 'has non-canonical JSON value' "$ARTIFACT_VALIDATOR"
require_present 'self-hash mismatch' "$ARTIFACT_VALIDATOR"
require_present 'records length must equal D11 grid length' "$ARTIFACT_VALIDATOR"
require_present 'route_coverage must prove all routed fixture axes' "$ARTIFACT_VALIDATOR"
require_present 'bpc must equal log2_sum / token_count' "$ARTIFACT_VALIDATOR"
require_present 'aggregate_parity_verdict must match derived' "$ARTIFACT_VALIDATOR"
require_present 'pareto_verdict must match derived' "$ARTIFACT_VALIDATOR"
require_present 'temporal_switch_digest.*transition_mass must be non-empty' "$ARTIFACT_VALIDATOR"
require_present 'frontier point.*quality.per_seed_val_bpc must contain 5 finite values' "$ARTIFACT_VALIDATOR"
require_present 'grad log record' "$ARTIFACT_VALIDATOR"
require_present 'grad log must contain.*completed-run JSONL records' "$ARTIFACT_VALIDATOR"
require_present 'schema must be s7_grad_log\.v1' "$ARTIFACT_VALIDATOR"
require_present 'grad_norms must match run-log grad_norms' "$ARTIFACT_VALIDATOR"
require_present 'GradNormSummary fields must be global_l2, max_l2, mean_l2' "$ARTIFACT_VALIDATOR"
require_present 'router-step telemetry must cover layers 0\.\.3' "$ARTIFACT_VALIDATOR"
require_present 'dense router-step telemetry must be empty' "$ARTIFACT_VALIDATOR"
require_present 'telemetry_self_hash' "$ARTIFACT_VALIDATOR"
require_present 'SWITCH_STATS_DOMAIN' "$ARTIFACT_VALIDATOR"
require_present 'FRONTIER_DOMAIN' "$ARTIFACT_VALIDATOR"
require_present 'BURN_GRAD_SMOKE_DOMAIN' "$ARTIFACT_VALIDATOR"
require_present 'ORACLE_ROUTED_DOMAIN' "$ARTIFACT_VALIDATOR"
require_present 'frontier_self_hash' "$ARTIFACT_VALIDATOR"
require_present 'smoke_self_hash' "$ARTIFACT_VALIDATOR"
require_present 'oracle_self_hash' "$ARTIFACT_VALIDATOR"
require_present 'completion must be Rust tagged S7Completion' "$ARTIFACT_VALIDATOR"
require_present 'losses length must be.*for completed run' "$ARTIFACT_VALIDATOR"
require_present 'RawLossDiagnostics fields must be lm_loss_raw' "$ARTIFACT_VALIDATOR"
require_present 'diagnostics_self_hash' "$ARTIFACT_VALIDATOR"
require_present 'train_step must match loss step' "$ARTIFACT_VALIDATOR"
require_present 'self-test-optimizer-steps' "$ARTIFACT_VALIDATOR" "$VERIFY_PACKET_SCRIPT"
require_present 'self-test-eval-every-steps' "$ARTIFACT_VALIDATOR" "$VERIFY_PACKET_SCRIPT"
require_present 'S7 ACPX review evidence: NEEDS_CHANGES' "$REVIEW_VALIDATOR"
require_present 'ALWAYS_ON_PERSONAS' "$REVIEW_VALIDATOR"
require_present 'missing required personas for' "$REVIEW_VALIDATOR"
require_present 'reviewed_head must match expected_head' "$REVIEW_VALIDATOR"
require_present 'allow-reviewed-head-ancestor-of' "$REVIEW_VALIDATOR"
require_present 'require-reviewed-diff-admin-only' "$REVIEW_VALIDATOR"
require_present 'reviewed_head is stale' "$REVIEW_VALIDATOR"
require_present 'PASS review has unresolved blocking finding' "$REVIEW_VALIDATOR"
require_present 'allowed_severities' "$REVIEW_VALIDATOR"
require_present 'severity must be one of' "$REVIEW_VALIDATOR"
require_present 'status must be one of' "$REVIEW_VALIDATOR"
require_present 'must be an object' "$REVIEW_VALIDATOR"
require_present 'transport.*acpx' "$REVIEW_VALIDATOR"
require_present 'command must record an ACPX invocation prefix' "$REVIEW_VALIDATOR"
require_present 'audit-bead-reviews\.py' "$VERIFY_PACKET_SCRIPT"
require_present 'audit-closure-deps\.py' "$VERIFY_PACKET_SCRIPT"
require_present 'allow-reviewed-head-ancestor-of' "$VERIFY_PACKET_SCRIPT"
require_present 'require-reviewed-diff-admin-only' "$VERIFY_PACKET_SCRIPT"
require_present 'S7 bead review coverage audit failed' "$VERIFY_PACKET_SCRIPT"
require_present 'S7 closure dependency audit failed' "$VERIFY_PACKET_SCRIPT"
require_present 'S7 bead review coverage: NEEDS_CHANGES' "$BEAD_REVIEW_AUDITOR"
require_present '--issues-file' "$BEAD_REVIEW_AUDITOR"
require_present 'reviewed_head must match expected_head' "$BEAD_REVIEW_AUDITOR"
require_present 'allow-reviewed-head-ancestor-of' "$BEAD_REVIEW_AUDITOR"
require_present 'require-reviewed-diff-admin-only' "$BEAD_REVIEW_AUDITOR"
require_present 'reviewed_head is stale' "$BEAD_REVIEW_AUDITOR"
require_present 'manager disposition' "$BEAD_REVIEW_AUDITOR"
require_present 'no additional acpx review required' "$BEAD_REVIEW_AUDITOR"
require_present 'non_blocking_review' "$BEAD_REVIEW_AUDITOR"
require_present 'missing .* review evidence' "$BEAD_REVIEW_AUDITOR"
require_present 's7_bead_acpx_review\.v1' "$BEAD_REVIEW_AUDITOR"
require_present 'DEFAULT_EVIDENCE_DIR' "$BEAD_REVIEW_AUDITOR"
require_present 'ALWAYS_ON_PERSONAS' "$BEAD_REVIEW_AUDITOR"
require_present 'missing always-on persona' "$BEAD_REVIEW_AUDITOR" "$S7_AUDIT_BEAD_REVIEWS_TEST"
require_present '--evidence-dir' "$BEAD_REVIEW_AUDITOR"
require_present 'S7 closure dependency audit: NEEDS_CHANGES' "$CLOSURE_DEP_AUDITOR"
require_present 'BLOCKING_DEP_TYPES' "$CLOSURE_DEP_AUDITOR"
require_present 'parent-child' "$CLOSURE_DEP_AUDITOR" "$S7_AUDIT_CLOSURE_DEPS_TEST"
require_present 'unresolved dependency' "$CLOSURE_DEP_AUDITOR" "$S7_AUDIT_CLOSURE_DEPS_TEST"
require_present 'S7 closure dependency disposition' "$CLOSURE_DEP_AUDITOR" "$S7_AUDIT_CLOSURE_DEPS_TEST"
require_present 's7_production_bundle_manifest\.v1' "$PACKET_ASSEMBLER"
require_present '--write-template' "$PACKET_ASSEMBLER"
require_present '--check-inputs' "$PACKET_ASSEMBLER"
require_present '--run-reviews' "$PACKET_ASSEMBLER"
require_present 'run-acpx-reviews\.py' "$PACKET_ASSEMBLER"
require_present '--preflight' "$PACKET_ASSEMBLER"
require_present 'preflight=True' "$PACKET_ASSEMBLER"
require_present 'non-dry-run production assembly requires --run-reviews' "$PACKET_ASSEMBLER"
require_present '--gemini-agent' "$PACKET_ASSEMBLER"
require_present '--claude-agent' "$PACKET_ASSEMBLER"
require_present 'missing_input_paths' "$PACKET_ASSEMBLER"
require_present 'relative bundle input path escapes manifest directory' "$PACKET_ASSEMBLER" "scripts/tests/s7_assemble_packet_test.sh"
require_present 'has unknown field\(s\)' "$PACKET_ASSEMBLER"
require_present 'materialize-run' "$PACKET_ASSEMBLER"
require_present 'materialize-support-artifact' "$PACKET_ASSEMBLER"
require_present 'derive-summaries' "$PACKET_ASSEMBLER"
require_present 'derive-comparison' "$PACKET_ASSEMBLER"
require_present 'derive-frontier' "$PACKET_ASSEMBLER"
require_present 'emit-report' "$PACKET_ASSEMBLER"
require_present 'require_report_decision' "$PACKET_ASSEMBLER"
require_present 'require_report_revision' "$PACKET_ASSEMBLER"
require_present '"decision": "ProceedToS8"' "$PACKET_ASSEMBLER"
require_present 'verify-packet\.sh' "$PACKET_ASSEMBLER"
require_present 'gemini --skip-trust -m gemini-3\.1-pro-preview --acp' "$ACPX_REVIEW_RUNNER"
require_present '--gemini-agent' "$ACPX_REVIEW_RUNNER"
require_present 'S7_GEMINI_ACP_AGENT' "$ACPX_REVIEW_RUNNER"
require_present '--preflight' "$ACPX_REVIEW_RUNNER"
require_present 'S7 ACPX review preflight' "$ACPX_REVIEW_RUNNER"
require_present '--bead-review' "$ACPX_REVIEW_RUNNER"
require_present 's7_bead_acpx_review\.v1' "$ACPX_REVIEW_RUNNER"
require_present 'DEFAULT_BEAD_REVIEW_PERSONAS' "$ACPX_REVIEW_RUNNER"
require_present 'review personas missing requested persona ids' "$ACPX_REVIEW_RUNNER" "$S7_RUN_ACPX_TEST"
require_present 'GEMINI_API_KEY' "$ACPX_REVIEW_RUNNER"
require_present 'oauth-personal' "$ACPX_REVIEW_RUNNER" "$S7_RUN_ACPX_TEST"
require_present '--claude-agent' "$ACPX_REVIEW_RUNNER"
require_present 'S7_CLAUDE_ACP_AGENT' "$ACPX_REVIEW_RUNNER"
require_present 'claude' "$ACPX_REVIEW_RUNNER"
require_present 'S7 ACPX review runner: NEEDS_CHANGES' "$ACPX_REVIEW_RUNNER"
require_present 'not writing PASS evidence' "$ACPX_REVIEW_RUNNER"
require_present 'defaults to the resolved --root' "$ACPX_REVIEW_RUNNER"
require_present 'run-acpx-reviews must not default ACPX reviews to a sibling checkout' "$S7_RUN_ACPX_TEST"
require_present 'validate_review_cwd_head' "$ACPX_REVIEW_RUNNER"
require_present 'ACPX review cwd HEAD mismatch' "$ACPX_REVIEW_RUNNER"
require_present 'validate-reviews\.py' "$ACPX_REVIEW_RUNNER"
require_present 'docs/review/f-s7/raw' "$ACPX_REVIEW_RUNNER"

"$ISOLATION_SCRIPT" --self-test >/dev/null
[[ -x "$PREREG_SCRIPT" ]] || {
  echo "schema discipline failed: $PREREG_SCRIPT must be executable" >&2
  exit 1
}
[[ -x "$VERIFY_PACKET_SCRIPT" ]] || {
  echo "schema discipline failed: $VERIFY_PACKET_SCRIPT must be executable" >&2
  exit 1
}
[[ -x "$PACKET_ASSEMBLER" ]] || {
  echo "schema discipline failed: $PACKET_ASSEMBLER must be executable" >&2
  exit 1
}
[[ -x "$ACPX_REVIEW_RUNNER" ]] || {
  echo "schema discipline failed: $ACPX_REVIEW_RUNNER must be executable" >&2
  exit 1
}
[[ -x "$REPORT_VALIDATOR" ]] || {
  echo "schema discipline failed: $REPORT_VALIDATOR must be executable" >&2
  exit 1
}
[[ -x "$REPORT_EMITTER" ]] || {
  echo "schema discipline failed: $REPORT_EMITTER must be executable" >&2
  exit 1
}
[[ -x "$ARTIFACT_VALIDATOR" ]] || {
  echo "schema discipline failed: $ARTIFACT_VALIDATOR must be executable" >&2
  exit 1
}
[[ -x "$REVIEW_VALIDATOR" ]] || {
  echo "schema discipline failed: $REVIEW_VALIDATOR must be executable" >&2
  exit 1
}
[[ -x "$BEAD_REVIEW_AUDITOR" ]] || {
  echo "schema discipline failed: $BEAD_REVIEW_AUDITOR must be executable" >&2
  exit 1
}

echo "S7 schema discipline: ok"
